### ISSUE TITLE
Lag goggles 13.0 warning message spam in console and crash warning

### ISSUE THREAD

**Issue by SilearFlare** [FalsePattern/LagGogglesLegacy#10]
I can get around the console spam, but the 
`This will be a crash in FalsePatternLib 0.11, update your code!`
has me more worried, considering we're at 0.10.10 already, so I thought I'd open an issue about it.

https://paste.ee/p/IsSXF

**Comment by FalsePattern** [comment]
Should be fixed in 4.13.1

**Comment by SilearFlare** [comment]
Welp, now everything just crashes at startup. 
https://mclo.gs/lZTtQxf
I get the same results from a barebones instance with only falsepatternlib+ lag goggles +sponge mixins and also my usual pack with only 4.13.1 updated from 4.13.0.
https://mclo.gs/1u4Y4Bt

**Comment by FalsePattern** [comment]
> Welp, now everything just crashes at startup. https://mclo.gs/lZTtQxf I get the same results from a barebones instance with only falsepatternlib+ lag goggles +sponge mixins and also my usual pack with only 4.13.1 updated from 4.13.0. https://mclo.gs/1u4Y4Bt

Remove SpongeMixins and upgrade to GasStation, SpongeMixins is no longer supported by my mods.
GasStation has spongemixins emulation, so mods that depend on spongemixins will just work with it.
https://github.com/FalsePattern/GasStation

**Comment by SilearFlare** [comment]
> Remove SpongeMixins and upgrade to GasStation, SpongeMixins is no longer supported by my mods.
Not an option, as it's not an upgrade, it's a different mod altogether.

I work with a truckload of bleeding edge **N**o**H**omo mods, especially their fork of spongemixins. Removing spongemixing stuff **will obviously break shit**, as they are prone to inbreeding and fixing issues in their mods by embedding fixes inside their other mods in a beautiful mess of christmas lights. 
It goes without saying that switching to your mod and disabling spongemixins crashes my game at startup with a different error.

Considering that the entire falsepattern suite worked just fine with spongers 1.5 I really hope you can give me another option, otherwise the only solution is just stop updating.

**Comment by FalsePattern** [comment]
I do not plan on providing compatibility with gtnh-specific mods, they need to fix this on their side.
