### ISSUE TITLE
Crash when trying to open Options

### ISSUE THREAD

**Issue by Serega007RU** [FalsePattern/LagGogglesLegacy#11]
When you try to open Options, the game crashes. What could be the problem?
![image](https://user-images.githubusercontent.com/64780091/194103573-ac46386c-c14c-448f-951e-dd230b8682e4.png)
[crash-2022-10-05_18.43.49-client.txt](https://github.com/FalsePattern/LagGogglesLegacy/files/9717110/crash-2022-10-05_18.43.49-client.txt)

**Comment by StrangeMan1580** [comment]
Yeah, same crash.
