### ISSUE TITLE
minecraft instantly closes upon startup

### ISSUE THREAD

**Issue by mcmso** [FalsePattern/LagGogglesLegacy#13]
no crash report, 
log:
[latest.log](https://github.com/FalsePattern/LagGogglesLegacy/files/10327889/latest.log)

version:00gasstation-mc1.7.10-0.5.1.jar
laggoggles-mc1.7.10-4.13.1.jar
falsepatternlib-mc1.7.10-0.10.13.jar

**Comment by FalsePattern** [comment]
The DragonRealm modpack has a bunch of messy ASM patches inside it. You'll have to ask Reika about this.

**Comment by mcmso** [comment]
> The DragonRealm modpack has a bunch of messy ASM patches inside it. You'll have to ask Reika about this.

Thank you for your reply. This issue should indeed be closed, which is of great help to me
Thank you

**Comment by FalsePattern** [comment]
> > The DragonRealm modpack has a bunch of messy ASM patches inside it. You'll have to ask Reika about this.
> 
> Thank you for your reply. This issue should indeed be closed, which is of great help to me Thank you

The DragonRealm modpack's warning page specifically says to relay all bug reports to Reika:
![Screenshot_2023-01-04_01-54-57](https://user-images.githubusercontent.com/30945458/210465201-a6f22e92-93bc-4b39-9bb8-f5a3735cf5d5.png)
