### ISSUE TITLE
Goggles rebalance

### ISSUE THREAD

**Issue by Houstonruss** [FalsePattern/LagGogglesLegacy#3]
I think that right now finding lag is too easy, and the recipe for lagvision goggles needs to be more expensive.

**Comment by FalsePattern** [comment]
![image](https://user-images.githubusercontent.com/30945458/170892912-2026a176-05d7-49cc-a01a-2398ac43dd2e.png)

**Comment by Houstonruss** [comment]
![image](https://user-images.githubusercontent.com/50430417/170892960-21e17fcb-64e4-4a47-a97d-3d2731ed8475.png)
