### ISSUE TITLE
Ultramine server tps scan no permission

### ISSUE THREAD

**Issue by simbiant** [FalsePattern/LagGogglesLegacy#8]
I'm running gtnh 2.1.2.3qf ultramine server on my second pc, and when I installed mod, there is no world button. Where do I need to give permissions. I am op on server
![image](https://user-images.githubusercontent.com/24406976/180150224-f3534f59-0875-4e2f-b645-1c9162209cb5.png)

**Comment by albertopirillo** [comment]
Same problem with GT:NH 2.1.2.0.
Except that mine is a Vanilla Forge Server and I'm literally the owner.

**Comment by maozelai** [comment]
Thermos also has this  problem
Same problem with GT:NH 2.1.2.4 pre18

**Comment by SirFell** [comment]
For custom cores please check #2. Third party server cores may (read as likely) use different mappings which are not supported. Either mod or server core needs to be recompiled with different mappings (ones used by the thing that isn't getting recompiled)

**Comment by albertopirillo** [comment]
Alright, and what about a Vanilla Forge server? It has the same issue, so there must be another problem.
And quite frankly, it's unclear what that button should do: "No perms". Ok, no perms for what?

**Comment by quentin452** [comment]
does the Ultramine server have laggoogles installed?, try update gtnh modpack

**Comment by simbiant** [comment]
Yes, It does. I tried with installed on server and without it

**Comment by quentin452** [comment]
the latest release now is [2.2.0.0-RC-1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/releases/tag/2.2.0.0-RC-1)

**Comment by simbiant** [comment]
I could try, but I don't think it'll solve the problem

**Comment by quentin452** [comment]
i will try with [2.1.2.3qf-test](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/releases/tag/2.1.2.3qf-test) if i have the problem

**Comment by quentin452** [comment]
i added falsepattern + laggogles but the modpack crash

**Comment by simbiant** [comment]
conflict with bugtorch, opis, mobious core. Delete them from mods folder

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
on my local server 2.1.2.3qf-test i can use the world profiler

**Comment by simbiant** [comment]
Can you upload your modpack, so I could test it? 2.1.2.3qf

**Comment by quentin452** [comment]
yes the serverpack and clientpack with mods and config ?

**Comment by simbiant** [comment]
Yeah

**Comment by quentin452** [comment]
serverpack : https://mega.nz/file/DgkkRBYZ#GvHctahln0NVSvM7gslXvtWQ7jsfZMtVbibaAzpoTDk
clientpack : https://mega.nz/file/bxc1ATSB#ImePRM8m1EyAjGU20xcoDlK-FZ7vROhu6dtM_enMMwU

**Comment by simbiant** [comment]
Thanks, I'll try it later

**Comment by quentin452** [comment]
> Thanks, I'll try it later

working?

**Comment by FalsePattern** [comment]
@simbiant any status updates?

**Comment by FalsePattern** [comment]
Closed as stale.
