### ISSUE TITLE
[1.7.10] LagGoogles crash with Dragonapi

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/LagGogglesLegacy#9]
crash report : 

https://paste.ee/p/uPTEl

mods list : 

DragonAPI 1.7.10 V31b
falsepatternlib-mc1.7.10-0.10.10
SpongeMixins-1.5.0
laggoggles-mc1.7.10-4.13.0

**Comment by FalsePattern** [comment]
The paste link you posted doesn't work. Can you please upload it again?
